"""Canonical normalization of Postman JSON.

Postman exports carry volatile fields (auto-generated ids, timestamps) and
non-deterministic key ordering, which make raw JSON diffs noisy and produce
spurious git churn. Normalizing before writing to git — and on both sides of a
diff — keeps commits and diffs meaningful.

Rules:
- Drop volatile keys (ids, timestamps) wherever they appear.
- Sort object keys deterministically.
- **Preserve array order** — request/folder order is meaningful, never sorted.
- Emit 2-space-indented JSON with a trailing newline.

``normalize`` is idempotent: normalizing already-normalized text is a no-op.
"""

from __future__ import annotations

import json
from typing import Any

#: Keys removed wherever they appear. These are auto-generated by Postman and
#: differ across exports / accounts, so they carry no shareable meaning.
VOLATILE_KEYS = frozenset(
    {
        "id",
        "_postman_id",
        "uid",
        "createdAt",
        "updatedAt",
        "_postman_exported_at",
        "_postman_exported_using",
    }
)


def strip_volatile(value: Any) -> Any:
    """Recursively return ``value`` with :data:`VOLATILE_KEYS` removed.

    Only *dict keys* are matched, so a Postman form field whose ``key`` happens
    to be ``"id"`` is untouched (its structural key is ``"key"``, not ``"id"``).
    """
    if isinstance(value, dict):
        return {k: strip_volatile(v) for k, v in value.items() if k not in VOLATILE_KEYS}
    if isinstance(value, list):
        return [strip_volatile(item) for item in value]
    return value


def dumps(value: Any) -> str:
    """Serialize an already-cleaned object to canonical JSON text."""
    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def normalize(value: Any) -> str:
    """Return canonical JSON text for a Postman object (strip + sort + format)."""
    return dumps(strip_volatile(value))


def normalize_text(text: str) -> str:
    """Normalize a JSON *string*. Useful for idempotency checks and re-formatting."""
    return normalize(json.loads(text))


def normalized_obj(value: Any) -> Any:
    """Return the volatile-stripped object (for structural comparison/diffing)."""
    return strip_volatile(value)
